modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"

[[mods]]
modId="temporalengineering"
version="1.0.0"
displayName="Temporal Engineering"
description='''Temporal Engineering adds heat-driven modular machines that generate Exotic Matter used to manipulate time. This is an MVP build for Forge 1.18.2.'''
authors="Pedro Schenegoski"
displayTest="MATCH_VERSION"

[[dependencies.temporalengineering]]
modId="forge"
mandatory=true
versionRange="[40.3.0]"
ordering="NONE"
side="BOTH"

[[dependencies.temporalengineering]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2]"
ordering="NONE"
side="BOTH"
